[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
bonk_arena = "CimnUFrTgq9DoGx9peefTU2bRvkQSMLwra8ZgexZ1WQG"
test_token = "6v21kxAmupFVoPcVFhYAvS65KAFkYrNWYdyLBzzAjhj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aronyu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
